# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enable corepack for yarn
      run: corepack enable
    - name: Setup corepack for yarn
      run: corepack prepare yarn@stable --activate
    - name: Install yarn
      run: yarn set version stable
    - name: Install
      run: yarn --immutable
    - name: Install package dependencies
      run: yarn workspace @eskawl/emotion-box install
    - name: Test
      run: yarn test
    - name: Coverage
      run: yarn coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: ./packages/emotion-box
        debug: true

